## 陣列初始與規劃

In [1]:
# ndarray.ndim：維度的數量
# ndarray.shape：顯示陣列在每個維度上的整數值
# ndarray.size：陣列內維數的總數
# ndarray.dtype：用來描述陣列中元素類型的對象

import numpy as np

data = np.array([[8, 4, 2],
                 [9, 6, 3],
                 [7, 4, 1]])

data.ndim, data.shape, data.size, data.dtype

# 第一個得出的數值2為以下兩種含義：
# 2階(rank)張量 tensor
# 2維(dim)陣列 array

(2, (3, 3), 9, dtype('int64'))

In [2]:
# Practice

import numpy as np

l = [ [1, 2, 3],
      [2, 3, 4]]

a = np.array(l)

print(a)
print('number of dim:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('size:', a.dtype)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6
size: int64


In [3]:
# 陣列初始化的方式

# 不做初始化
print(np.empty((2, 4)))

# 全部規劃為0
print(np.zeros((3, 4)))

# 全部規劃為1
print(np.ones((5, 2)))

# 全部規劃／填滿為某數，例如6
print(np.full((3, 3), 6))

# 對角
print(np.eye(3))

# 建立對角矩陣，對角為1,2,3,4，其他為0
print(np.diag([1, 2, 3, 4]))

[[-2.00000000e+000 -2.00000000e+000  6.93001367e-310  4.94065646e-324]
 [ 8.11978949e-312  6.93001427e-310  3.50977866e+064  5.56268465e-309]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [4]:
# reshape：可將現有的陣列重新規劃為x乘以y的陣列

import numpy as np
data = np.array([
                 [8, 4, 2, 1], 
                 [9, 6, 3, 0]
                 ])
data.shape

(2, 4)

In [7]:
# 根據上述，執行reshape（相乘後的值一定要相同！！！）
data.reshape(4, 2)

array([[8, 4],
       [2, 1],
       [9, 6],
       [3, 0]])

In [5]:
# 承上，reshape(-1, 1)，負號在前方，陣列為直向
data.reshape(8, 1), data.reshape(-1, 1)

(array([[8],
        [4],
        [2],
        [1],
        [9],
        [6],
        [3],
        [0]]),
 array([[8],
        [4],
        [2],
        [1],
        [9],
        [6],
        [3],
        [0]]))

In [6]:
# 承上，reshape(1, -1)，負號在後方，陣列為橫向
data.reshape(1, 8), data.reshape(1, -1)

(array([[8, 4, 2, 1, 9, 6, 3, 0]]), array([[8, 4, 2, 1, 9, 6, 3, 0]]))

In [11]:
# 加強觀念
# 轉成陣列的優點為可計算總平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

import numpy as np
np.array(scores)

array([[90, 92, 95, 90],
       [89, 88, 85, 80],
       [75, 77, 78, 70]])

In [12]:
# 承上，使用np.mean計算總平均
np.mean(scores)

84.08333333333333

In [9]:
# 承上題，如果使用sum加總？（二維以上無法直接使用）
scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]
sum(scores)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [8]:
# 一維可直接使用sum加總
students = [90, 92, 95, 90]
sum(students)

367

In [4]:
# 每個list計算平均

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print(scores[0, :]) # 第一列的全部

np.mean(scores[0, :]), \
np.mean(scores[1, :]), \
np.mean(scores[2, :])

[90 92 95 90]


(91.75, 85.5, 75.0)

In [12]:
# Practice
# 使用list迴圈計算平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

for s in scores:
    print(sum(s) / len(s))

91.75
85.5
75.0


In [13]:
# Practice
# 使用list comprehension計算平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

[(sum(s) / len(s)) for s in scores]

[91.75, 85.5, 75.0]

In [15]:
# 每個list計算平均的最快用法
# 上下axis = 0, 左右axis = 1

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print(np.mean(scores, axis = 1))
print(np.mean(scores, axis = 0))

[91.75 85.5  75.  ]
[84.66666667 85.66666667 86.         80.        ]


In [5]:
# 如果要轉換成(12,) 1-rank tensor(1-dim array)
# flatten()返回一個摺疊成一維的陣列

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.flatten(), scores.ravel() # flatten與ravel執行後結果相同

(array([90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]),
 array([90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]))

In [3]:
# 如果要轉換成(12, 1) 2-rank tensor(2-dim array)

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.reshape(12, 1), scores.reshape(-1, 1) # 兩種皆可

(array([[90],
        [92],
        [95],
        [90],
        [89],
        [88],
        [85],
        [80],
        [75],
        [77],
        [78],
        [70]]),
 array([[90],
        [92],
        [95],
        [90],
        [89],
        [88],
        [85],
        [80],
        [75],
        [77],
        [78],
        [70]]))

In [4]:
# 如果要轉換成(1, 12) 2-rank tensor(2-dim array)

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.reshape(1, 12)

array([[90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]])

In [10]:
# flatten與ravel不同！！！
# flatten()：返回的是副本，對副本所做的修改不會影響原始矩陣
# ravel()：會影響原始矩陣

x = np.array([[1, 2], [3, 4]])
print(x.shape)

x.flatten()[1] = 100
print(x)

x.ravel()[1] = 100
print(x)

(2, 2)
[[1 2]
 [3 4]]
[[  1 100]
 [  3   4]]


In [4]:
# np.arange(起始, 結束, 固定間隔)：產生1-dim array，與np.array()差別在np.arange有較大彈性。

# list操作(無法以浮點數當間隔)
print(list(range(1, 10, 1)))

# numpy操作
import numpy as np
print(list(np.arange(1, 10, 0.5)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]


In [5]:
# np.linspace(起始, 結束, 起始與結束的區間內產生幾個元素)：只要給定陣列區間，就可指定在這區間內產生幾個元素，包含結束值
# np.linspace(起始, 結束, 起始與結束的區間內產生幾個元素, endpoint = False)：不包含結束值
import numpy as np
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [6]:
# Practice

import numpy as np

x = np.empty((2, 4))
print(x)
print('-----')
y = np.zeros((3, 2))
print(y)
print('-----')
z = np.ones((2, 5))
print(z)

[[-2.00000000e+000  1.49457320e-154  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  5.60601841e-309]]
-----
[[0. 0.]
 [0. 0.]
 [0. 0.]]
-----
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# Practice

import numpy as np

x = np.eye(6)
print(x)
print('-----')
y = np.diag([1, 2, 3, 4])
print(y)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
-----
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
# Practice

import numpy as np

w = np.linspace(1, 10, 6).reshape((3, 2))
print(w)
print('-----')
x = np.linspace(1, 10, 6).reshape((2, 3))
print(x)
print('-----')
y = np.arange(8).reshape((2, 4))
print(y)
print('-----')
z = np.arange(8).reshape((4, 2))
print(z)

[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
-----
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
-----
[[0 1 2 3]
 [4 5 6 7]]
-----
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [11]:
# Practice
# 不包含結束值30

import numpy as np

r1 = np.arange(25, 30, .5)
print('r1=>', r1)

r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [12]:
# Practice
# 包含結束值5

import numpy as np

r1 = np.linspace(3, 5, 9)
print('r1=>', r1)

r1=> [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
