## 陣列初始與規劃

In [1]:
# ndarray.ndim：維度的數量
# ndarray.shape：顯示陣列在每個維度上的整數值
# ndarray.size：陣列內維數的總數
# ndarray.dtype：用來描述陣列中元素類型的對象

import numpy as np

data = np.array([[8, 4, 2],
                 [9, 6, 3],
                 [7, 4, 1]])

data.ndim, data.shape, data.size, data.dtype

# 第一個得出的數值2為以下兩種含義：
# 2階(rank)張量 tensor
# 2維(dim)陣列 array

(2, (3, 3), 9, dtype('int64'))

In [2]:
# Practice

import numpy as np

l = [ [1, 2, 3],
      [2, 3, 4]]

a = np.array(l)

print(a)
print('number of dim:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('size:', a.dtype)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6
size: int64


In [3]:
# 陣列初始化的方式

# 不做初始化
print(np.empty((2, 4)))

# 全部規劃為0
print(np.zeros((3, 4)))

# 全部規劃為1
print(np.ones((5, 2)))

# 全部規劃／填滿為某數，例如6
print(np.full((3, 3), 6))

# 對角
print(np.eye(3))

# 建立對角矩陣，對角為1,2,3,4，其他為0
print(np.diag([1, 2, 3, 4]))

[[-2.00000000e+000 -2.00000000e+000  6.93001367e-310  4.94065646e-324]
 [ 8.11978949e-312  6.93001427e-310  3.50977866e+064  5.56268465e-309]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [4]:
# reshape：可將現有的陣列重新規劃為x乘以y的陣列

import numpy as np
data = np.array([
                 [8, 4, 2, 1], 
                 [9, 6, 3, 0]
                 ])
data.shape

(2, 4)

In [7]:
# 根據上述，執行reshape（相乘後的值一定要相同！！！）
data.reshape(4, 2)

array([[8, 4],
       [2, 1],
       [9, 6],
       [3, 0]])

In [5]:
# 承上，reshape(-1, 1)，負號在前方，陣列為直向
data.reshape(8, 1), data.reshape(-1, 1)

(array([[8],
        [4],
        [2],
        [1],
        [9],
        [6],
        [3],
        [0]]),
 array([[8],
        [4],
        [2],
        [1],
        [9],
        [6],
        [3],
        [0]]))

In [6]:
# 承上，reshape(1, -1)，負號在後方，陣列為橫向
data.reshape(1, 8), data.reshape(1, -1)

(array([[8, 4, 2, 1, 9, 6, 3, 0]]), array([[8, 4, 2, 1, 9, 6, 3, 0]]))

In [11]:
# 加強觀念
# 轉成陣列的優點為可計算總平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

import numpy as np
np.array(scores)

array([[90, 92, 95, 90],
       [89, 88, 85, 80],
       [75, 77, 78, 70]])

In [12]:
# 承上，使用np.mean計算總平均
np.mean(scores)

84.08333333333333

In [9]:
# 承上題，如果使用sum加總？（二維以上無法直接使用）
scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]
sum(scores)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [8]:
# 一維可直接使用sum加總
students = [90, 92, 95, 90]
sum(students)

367

In [4]:
# 每個list計算平均

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print(scores[0, :]) # 第一列的全部

np.mean(scores[0, :]), \
np.mean(scores[1, :]), \
np.mean(scores[2, :])

[90 92 95 90]


(91.75, 85.5, 75.0)

In [12]:
# Practice
# 使用list迴圈計算平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

for s in scores:
    print(sum(s) / len(s))

91.75
85.5
75.0


In [13]:
# Practice
# 使用list comprehension計算平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

[(sum(s) / len(s)) for s in scores]

[91.75, 85.5, 75.0]

In [15]:
# 每個list計算平均的最快用法
# 上下axis = 0, 左右axis = 1

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print(np.mean(scores, axis = 1))
print(np.mean(scores, axis = 0))

[91.75 85.5  75.  ]
[84.66666667 85.66666667 86.         80.        ]


In [5]:
# 如果要轉換成(12,) 1-rank tensor(1-dim array)
# flatten()返回一個摺疊成一維的陣列

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.flatten(), scores.ravel() # flatten與ravel執行後結果相同

(array([90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]),
 array([90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]))

In [3]:
# 如果要轉換成(12, 1) 2-rank tensor(2-dim array)

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.reshape(12, 1), scores.reshape(-1, 1) # 兩種皆可

(array([[90],
        [92],
        [95],
        [90],
        [89],
        [88],
        [85],
        [80],
        [75],
        [77],
        [78],
        [70]]),
 array([[90],
        [92],
        [95],
        [90],
        [89],
        [88],
        [85],
        [80],
        [75],
        [77],
        [78],
        [70]]))

In [4]:
# 如果要轉換成(1, 12) 2-rank tensor(2-dim array)

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.reshape(1, 12)

array([[90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]])

In [10]:
# flatten與ravel不同！！！
# flatten()：返回的是副本，對副本所做的修改不會影響原始矩陣
# ravel()：會影響原始矩陣

x = np.array([[1, 2], [3, 4]])
print(x.shape)

x.flatten()[1] = 100
print(x)

x.ravel()[1] = 100
print(x)

(2, 2)
[[1 2]
 [3 4]]
[[  1 100]
 [  3   4]]
