## 陣列初始與規劃

In [1]:
# ndarray.ndim：維度的數量
# ndarray.shape：顯示陣列在每個維度上的整數值
# ndarray.size：陣列內維數的總數
# ndarray.dtype：用來描述陣列中元素類型的對象

import numpy as np

data = np.array([[8, 4, 2],
                 [9, 6, 3],
                 [7, 4, 1]])

data.ndim, data.shape, data.size, data.dtype

# 第一個得出的數值2為以下兩種含義：
# 2階(rank)張量 tensor
# 2維(dim)陣列 array

(2, (3, 3), 9, dtype('int64'))

In [2]:
# Practice

import numpy as np

l = [ [1, 2, 3],
      [2, 3, 4]]

a = np.array(l)

print(a)
print('number of dim:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('size:', a.dtype)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6
size: int64


In [3]:
# 陣列初始化的方式

# 不做初始化
print(np.empty((2, 4)))

# 全部規劃為0
print(np.zeros((3, 4)))

# 全部規劃為1
print(np.ones((5, 2)))

# 全部規劃／填滿為某數，例如6
print(np.full((3, 3), 6))

# 對角
print(np.eye(3))

# 建立對角矩陣，對角為1,2,3,4，其他為0
print(np.diag([1, 2, 3, 4]))

[[-2.00000000e+000 -2.00000000e+000  6.93001367e-310  4.94065646e-324]
 [ 8.11978949e-312  6.93001427e-310  3.50977866e+064  5.56268465e-309]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [4]:
# reshape：可將現有的陣列重新規劃為x乘以y的陣列

import numpy as np
data = np.array([
                 [8, 4, 2, 1], 
                 [9, 6, 3, 0]
                 ])
data.shape

(2, 4)

In [7]:
# 根據上述，執行reshape（相乘後的值一定要相同！！！）
data.reshape(4, 2)

array([[8, 4],
       [2, 1],
       [9, 6],
       [3, 0]])

In [5]:
# 承上，reshape(-1, 1)，負號在前方，陣列為直向
data.reshape(8, 1), data.reshape(-1, 1)

(array([[8],
        [4],
        [2],
        [1],
        [9],
        [6],
        [3],
        [0]]),
 array([[8],
        [4],
        [2],
        [1],
        [9],
        [6],
        [3],
        [0]]))

In [6]:
# 承上，reshape(1, -1)，負號在後方，陣列為橫向
data.reshape(1, 8), data.reshape(1, -1)

(array([[8, 4, 2, 1, 9, 6, 3, 0]]), array([[8, 4, 2, 1, 9, 6, 3, 0]]))

In [11]:
# 加強觀念
# 轉成陣列的優點為可計算總平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

import numpy as np
np.array(scores)

array([[90, 92, 95, 90],
       [89, 88, 85, 80],
       [75, 77, 78, 70]])

In [12]:
# 承上，使用np.mean計算總平均
np.mean(scores)

84.08333333333333

In [9]:
# 承上題，如果使用sum加總？（二維以上無法直接使用）
scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]
sum(scores)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [8]:
# 一維可直接使用sum加總
students = [90, 92, 95, 90]
sum(students)

367

In [4]:
# 每個list計算平均

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print(scores[0, :]) # 第一列的全部

np.mean(scores[0, :]), \
np.mean(scores[1, :]), \
np.mean(scores[2, :])

[90 92 95 90]


(91.75, 85.5, 75.0)

In [12]:
# Practice
# 使用list迴圈計算平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

for s in scores:
    print(sum(s) / len(s))

91.75
85.5
75.0


In [13]:
# Practice
# 使用list comprehension計算平均

scores = [[90, 92, 95, 90], 
          [89, 88, 85, 80],
          [75, 77, 78, 70]]

[(sum(s) / len(s)) for s in scores]

[91.75, 85.5, 75.0]

In [15]:
# 每個list計算平均的最快用法
# 上下axis = 0, 左右axis = 1

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print(np.mean(scores, axis = 1))
print(np.mean(scores, axis = 0))

[91.75 85.5  75.  ]
[84.66666667 85.66666667 86.         80.        ]


In [5]:
# 如果要轉換成(12,) 1-rank tensor(1-dim array)
# flatten()返回一個摺疊成一維的陣列

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.flatten(), scores.ravel() # flatten與ravel執行後結果相同

(array([90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]),
 array([90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]))

In [3]:
# 如果要轉換成(12, 1) 2-rank tensor(2-dim array)

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.reshape(12, 1), scores.reshape(-1, 1) # 兩種皆可

(array([[90],
        [92],
        [95],
        [90],
        [89],
        [88],
        [85],
        [80],
        [75],
        [77],
        [78],
        [70]]),
 array([[90],
        [92],
        [95],
        [90],
        [89],
        [88],
        [85],
        [80],
        [75],
        [77],
        [78],
        [70]]))

In [4]:
# 如果要轉換成(1, 12) 2-rank tensor(2-dim array)
## 留意與(12,) 1-rank tensor很像，但此差異處為多了一層[]。

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores.reshape(1, 12)

array([[90, 92, 95, 90, 89, 88, 85, 80, 75, 77, 78, 70]])

In [10]:
# flatten與ravel不同！！！
# flatten()：返回的是副本，對副本所做的修改不會影響原始矩陣
# ravel()：會影響原始矩陣

x = np.array([[1, 2], [3, 4]])
print(x.shape)

x.flatten()[1] = 100
print(x)

x.ravel()[1] = 100
print(x)

(2, 2)
[[1 2]
 [3 4]]
[[  1 100]
 [  3   4]]


In [4]:
# np.arange(起始, 結束, 固定間隔)：產生1-dim array，與np.array()差別在np.arange有較大彈性。

# list操作(無法以浮點數當間隔)
print(list(range(1, 10, 1)))

# numpy操作
import numpy as np
print(list(np.arange(1, 10, 0.5)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]


In [5]:
# np.linspace(起始, 結束, 起始與結束的區間內產生幾個元素)：只要給定陣列區間，就可指定在這區間內產生幾個元素，包含結束值
# np.linspace(起始, 結束, 起始與結束的區間內產生幾個元素, endpoint = False)：不包含結束值
import numpy as np
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [6]:
# Practice

import numpy as np

x = np.empty((2, 4))
print(x)
print('-----')
y = np.zeros((3, 2))
print(y)
print('-----')
z = np.ones((2, 5))
print(z)

[[-2.00000000e+000  1.49457320e-154  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  5.60601841e-309]]
-----
[[0. 0.]
 [0. 0.]
 [0. 0.]]
-----
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# Practice

import numpy as np

x = np.eye(6)
print(x)
print('-----')
y = np.diag([1, 2, 3, 4])
print(y)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
-----
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
# Practice

import numpy as np

w = np.linspace(1, 10, 6).reshape((3, 2))
print(w)
print('-----')
x = np.linspace(1, 10, 6).reshape((2, 3))
print(x)
print('-----')
y = np.arange(8).reshape((2, 4))
print(y)
print('-----')
z = np.arange(8).reshape((4, 2))
print(z)

[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
-----
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
-----
[[0 1 2 3]
 [4 5 6 7]]
-----
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [11]:
# Practice
# 不包含結束值30

import numpy as np

r1 = np.arange(25, 30, .5)
print('r1=>', r1)

r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [12]:
# Practice
# 包含結束值5

import numpy as np

r1 = np.linspace(3, 5, 9)
print('r1=>', r1)

r1=> [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [1]:
# Practice

import numpy as np

a = np.array([6, 7, 8, 9])
b = np.arange(4)
c = a - b
print('a=>', a)
print('b=>', b)
print('c=>', c)
d = b**2
print('d=>', d)

a=> [6 7 8 9]
b=> [0 1 2 3]
c=> [6 6 6 6]
d=> [0 1 4 9]


In [5]:
# Practice, Boolean Indexing
# important!!!
# 尋找元素值，<=3

f = np.array([5, -1, 3, 9, 0])

## 其他語言寫法

for i in f:
    if i <= 3:
        print(i)


## python寫法

# 找出boolean
indexer = (f <= 3)
print(indexer)

# 利用boolean快速取出數值
(f[indexer])

-1
3
0
[False  True  True False  True]


array([-1,  3,  0])

In [10]:
# 承上題，一般寫法

f = np.array([5, -1, 3, 9, 0])
print(f[f <= 3]) # 直接印出小於等於3

f[f <= 3] = 1 # 將小於等於3轉換成1再印出
print(f)

[-1  3  0]
[5 1 1 9 1]


In [11]:
# Practice

import numpy as np
a = np.array([6, 7, 8, 9])
a += 2
print(a)

[ 8  9 10 11]


In [21]:
# Practice
# >=85有幾個(三種寫法)

import numpy as np

scores = np.array([[90, 92, 95, 90],
                   [89, 85, 88, 80],
                   [75, 77, 78, 70]])

print(scores[scores >= 85].shape[0])

# sum的用法是將True加總
print(scores >= 85)
print((scores >= 85).sum())
print(np.sum(scores >= 85, axis = None))

7
[[ True  True  True  True]
 [ True  True  True False]
 [False False False False]]
7
7


## 指定與重設

In [1]:
# 間隔選取[頭：尾：幾個]

import numpy as np

data = np.array([90, 92, 95, 90, 89, 88, 85, 80, 75, 78, 77, 70])
data[ : : ]

array([90, 92, 95, 90, 89, 88, 85, 80, 75, 78, 77, 70])

In [2]:
# 每兩個取一個值

import numpy as np

data = np.array([90, 92, 95, 90, 89, 88, 85, 80, 75, 78, 77, 70])
data[ : : 2]

array([90, 95, 89, 85, 75, 77])

In [3]:
# 遇到負號，則倒序（由尾到頭）

import numpy as np

data = np.array([90, 92, 95, 90, 89, 88, 85, 80, 75, 78, 77, 70])
data[ : : -1]

array([70, 77, 78, 75, 80, 85, 88, 89, 90, 95, 92, 90])

In [4]:
# 指定位置[row, column]，僅適用於2-rank tensor(2-dim array)

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[ : , : ] # 全部上下，全部左右

array([[90, 92, 95, 90],
       [89, 88, 85, 80],
       [75, 77, 78, 70]])

In [6]:
# 承上，指定位置[row, column]

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[ :2, :2] # 第0列取前兩個，第0行取前兩個

array([[90, 92],
       [89, 88]])

In [7]:
# 承上，指定位置[row, column]

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[-1, : ] # 第2列的全部

array([[75, 77, 78, 70]])

In [8]:
# 承上，指定位置[row, column]

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[1: , : ] # 第1列之後的全部

array([[89, 88, 85, 80],
       [75, 77, 78, 70]])

In [19]:
# test，取出第0列第0和2個，第2列第0和2個

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[ : :2, : :2]

array([[90, 95],
       [75, 78]])

In [22]:
# test，取出第0列第0和3個，第2列第0和3個

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[ : :2, : :3]

array([[90, 90],
       [75, 70]])

In [23]:
# Fancy Indexing
# 如遇無規則取值，僅能以下方式操作

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

scores[[0, -1, -1, 0], [0, -1, 0, -1]]

array([90, 70, 75, 90])

In [24]:
# Practice

import numpy as np

a = np.array([[1, 2, 3],
              [3, 6, 9],
              [2, 4, 6]])

print(a)
print('---------')
print(a[0])
print('---------')
print(a[1, 2])

[[1 2 3]
 [3 6 9]
 [2 4 6]]
---------
[1 2 3]
---------
9


In [25]:
# Practice

import numpy as np

a = np.array([[1, 2, 3],
              [3, 6, 9],
              [2, 4, 6]])

print(a[1, 1:3])
print('---------')
print(a[ : , 1])
print('---------')
a[1, 2] = 7
print(a)
print('---------')
a[ : , 0] = [0, 9, 8]
print(a)

[6 9]
---------
[2 6 4]
---------
[[1 2 3]
 [3 6 7]
 [2 4 6]]
---------
[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [26]:
# 觀念加強：1-rank tensor = list

import numpy as np

a = np.array([1, 2, 3, 4, 5])
a[ : ],a[1:3],a[1],a[3]

(array([1, 2, 3, 4, 5]), array([2, 3]), 2, 4)

In [27]:
# Practice：陣列指定位置取值-給予一個整數

import numpy as np

a = np.array([[ 0, 1, 2, 3, 4, 5],
              [10,11,12,13,14,15],
              [20,21,22,23,24,25],
              [30,31,32,33,34,35],
              [40,41,42,43,44,45],
              [50,51,52,53,54,55],])

print("--1--")
print(a[0,3:5]) # 第0個row, 第3,4個column
print("--2--")
print(a[4:,4:]) # 第4個以後的row, 第4個以後的column
print("--3--")
print(a[:3,:3]) # 前三個row, 前三個column
print("--4--")
print(a[:,2])   # 全部的row, 第2個column

--1--
[3 4]
--2--
[[44 45]
 [54 55]]
--3--
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
--4--
[ 2 12 22 32 42 52]


In [28]:
# Practice：陣列指定位置取值-tuple或list

import numpy as np

a = np.array([[ 0, 1, 2, 3, 4, 5],
              [10,11,12,13,14,15],
              [20,21,22,23,24,25],
              [30,31,32,33,34,35],
              [40,41,42,43,44,45],
              [50,51,52,53,54,55],])

print("--1--")
print(a[(0,1,2,3,4),(1,2,3,4,5)]) # 對應的位置：(0,1),(1,2),(2,3),(3,4),(4,5)
print("--2--")
print(a[3:,[0, 2, 5]]) # 第3個row以後, 第0,2,5個column

--1--
[ 1 12 23 34 45]
--2--
[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [29]:
# resize(arr1, shape1)：依據原本的陣列再設定指定大小的新陣列。
# arr1：原本的陣列，shape1：新規劃的大小

#reshape操作
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]
             ])

print(a)
print(a.shape)
print('------')
b = a.reshape(3,2) # --->此處再加上.copy()，就能將a、b分隔兩個陣列，不會產生連動！！！
print(b)
print(b.shape)
print('------')
a[0,1]=100
print(a)
print(b) # 因為a、b僅是shape不同，但是內容相同，因此若改到a，則b會連動。
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
------
[[  1 100   3]
 [  4   5   6]]
[[  1 100]
 [  3   4]
 [  5   6]]
(3, 2)


In [31]:
# 承上

#resize操作
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)
print(a.shape)
print('------')
b = np.resize(a, (3,3)) # 多出來就重複遞補
print(b)
print(b.shape)
print('------')
a[0,1] = 100 
print(b) # .resize()為建立新的陣列，因此無連動影響。
print(b.shape)
print(a.shape)
print(a)

[[1 2 3]
 [4 5 6]]
(2, 3)
------
[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)
------
[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)
(2, 3)
[[  1 100   3]
 [  4   5   6]]


## 數值計算與處理

In [1]:
# np.add()：加，亦可使用+
# np.subtract()：減，亦可使用-
# np.multiply()：乘，亦可使用*
# np.divide()：除，亦可使用/

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
             ])

b = np.array([10,10,10])
c = np.add(a, b)
print(c)
print('------')
d = np.subtract(a, b)
print(d)
print('------')
f = np.multiply(a, b)
print(f)
print('------')
g = np.divide(a, b)
print(g)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
------
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
------
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [2]:
# Practice

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
             ])

b = np.array([10, 10, 10])
c = a + b
print(c)
print('------')
d = a - b
print(d)
print('------')
f = a * b
print(f)
print('------')
g = a / b
print(g)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
------
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
------
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [3]:
# np.power(a, n)：a陣列的次方，亦可a**n 

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [4]:
# np.reciprocal()：倒數的計算，倒數是指a*b=1，輸入a後求b。分之一

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

1 / a

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [5]:
# Practice

import numpy as np

a = np.array([4, 5, 6])
print(a)
print('------')
b = np.power(a, 2)
print(b)
print('------')
c = np.array([1, 2, 3])
d = np.power(a, c)
print(d)
print('------')
h = a ** c # 次方
print(h)

[4 5 6]
------
[16 25 36]
------
[  4  25 216]
------
[  4  25 216]


In [6]:
# Practice

import numpy as np

a = np.array([0.25, 1.33, 1, -0.1, 100])
print(a)
print('------')
b = np.reciprocal(a)
print(b)
print('------')
1 / a # --->等同b的結果

[  0.25   1.33   1.    -0.1  100.  ]
------
[  4.          0.7518797   1.        -10.          0.01     ]
------


array([  4.       ,   0.7518797,   1.       , -10.       ,   0.01     ])

In [9]:
# np.around()：代表四捨五入
# decimals小數位數，預設為0，如果為負數，左邊的正整數將依序四捨五入進位。

import numpy as np

print(np.around([1.5, 2.5], decimals = 0))
print(np.around([-0.5, 0.5], decimals = 1))

[2. 2.]
[-0.5  0.5]


In [11]:
# np.floor()：回傳不大於輸入參數的最大整數。無條件捨去
# np.ceil()：回傳大於輸入參數的最小整數。無條件進位

import numpy as np

print(np.floor([1.234, 1.998]))
print(np.ceil([1.234, 1.998]))

[1. 1.]
[2. 2.]


In [12]:
# np.mod(a, b) = np.remainder()：代表a除以b的餘數。

import numpy as np

a = np.array([10, 20, 30])
b = np.array([3, 5, 7])
print(a % b)
print('------')
c = np.mod(a, b)
print(c)
print('------')
d = np.remainder(a, b)
print(d)

[1 0 2]
------
[1 0 2]
------
[1 0 2]


In [13]:
# practice

import numpy as np

a = np.array([1.0, 5.45, 123, 0.567, 25.532])
print(a)
print('------')
b = np.around(a)
print(b)
print(np.around(a, decimals = 1) ) # 小數點下一位
print(np.around(a, decimals = -1)) # 十位數
print(np.around(a, decimals = -2)) # 百位數

[  1.      5.45  123.      0.567  25.532]
------
[  1.   5. 123.   1.  26.]
[  1.    5.4 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
[  0.   0. 100.   0.   0.]


In [1]:
# Practice

import numpy as np
a = np.array([-1.7, 1.5, -0.2, 0.6, 10])
print(a)
print('------')
b=np.floor(a)
print(b)
print('------')
c=np.ceil(a)
print(c)

[-1.7  1.5 -0.2  0.6 10. ]
------
[-2.  1. -1.  0. 10.]
------
[-1.  2. -0.  1. 10.]


In [6]:
# np.max()：某個陣列內容的最大值，也可指定陣列的哪一軸(axis)內容的最大值。
# np.min()：某個陣列內容的最小值，也可指定陣列的哪一軸(axis)內容的最小值。
# np.sum()：某個陣列內容的總和，也可指定陣列的哪一軸(axis)內容的總和。

import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

print('全部最高分',np.max(scores))
print('每個column的最高分', np.max(scores, axis = 0))
print('每個row的最高分', np.max(scores, axis = 1))

全部最高分 95
每個column的最高分 [90 92 95 90]
每個row的最高分 [95 89 78]


In [7]:
# Practice

import numpy as np

a = np.array([[ 0, 30, 45],
              [60, 75, 90]])

print(a)
print("---------------")
b = np.sum(a)
print(b)
print("---------------")
b = np.sum(a, axis = 0)
print(b)
print("---------------")
b = np.sum(a, axis = 1)
print(b)

[[ 0 30 45]
 [60 75 90]]
---------------
300
---------------
[ 60 105 135]
---------------
[ 75 225]


In [8]:
# Practice

import numpy as np

a = np.array([[ 0, 30, 45],
              [60, 75, 90]])

print(a)
print("---------------")
b = np.max(a)
print(b)
print("---------------")
b = np.max(a, axis = 0)
print(b)
print("---------------")
b = np.max(a, axis = 1)
print(b)

[[ 0 30 45]
 [60 75 90]]
---------------
90
---------------
[60 75 90]
---------------
[45 90]


In [9]:
# mean()：取出陣列或陣列中指定的軸之平均數。

# 每一個權重都相同
import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])


np.mean(scores, axis = 1)

array([91.75, 85.5 , 75.  ])

In [11]:
# average()：方法與mean相似，可加入權重進行計算。
# 參數-> weights：權重，若沒有則設定為1。
#       returned：若設定為True，返回計算結果、權重相加總和，若無設定或設定False，則只計算結果。

# 每一個權重都不同，利用np.average計算三個row的平均數。
import numpy as np

scores = np.array([[90, 92, 95, 90], 
                   [89, 88, 85, 80],
                   [75, 77, 78, 70]])

w = np.array([0.2, 0.2, 0.2, 0.4])

np.average(scores, axis = 1, weights = w)

array([91.4, 84.4, 74. ])

In [12]:
# median()：取出陣列或陣列中指定的軸之中位數。
# 把所有值高低排序後，找出正中間作為中位數；如果資料數為偶數，則取最中間的兩個數值的平均數。

import numpy as np

a = np.array([[ 0, 30, 45],
              [60, 75, 90]])

print(a)
print("---------------")
b = np.median(a)
print(b)
print("---------------")
b = np.median(a, axis = 0)
print(b)
print("---------------")
b = np.median(a, axis = 1)
print(b)

[[ 0 30 45]
 [60 75 90]]
---------------
52.5
---------------
[30.  52.5 67.5]
---------------
[30. 75.]


In [13]:
# Practice

import numpy as np

a = np.array([[ 0, 30, 45],
              [60, 75, 90]])

print(a)
print("---------------")
b = np.mean(a)
print(b)
print("---------------")
b = np.mean(a, axis = 0)
print(b)
print("---------------")
b = np.mean(a, axis = 1)
print(b)

[[ 0 30 45]
 [60 75 90]]
---------------
50.0
---------------
[30.  52.5 67.5]
---------------
[25. 75.]


In [14]:
# Practice

import numpy as np

a = np.array([1,2,3,4])
b = np.average(a)
print(b)
print("---------")
wts = np.array([4,3,2,1])
b = np.average(a, weights = wts)
print(b)
print("---------")
b = np.average(       a = [1,2,3,4],
               weights  = [4,3,2,1], 
               returned = True)
print(b)

2.5
---------
2.0
---------
(2.0, 10.0)


In [16]:
# 觀念強調
# True代表除了計算結果，也使權重相加。

a = np.array([2,2,3,4])
wts = np.array([4,3,2,1])

b = np.average(a, weights = wts, returned = True)
print(b)

c  =  np.average(a, weights = wts, returned = False)
print(c)

(2.4, 10.0)
2.4
