## 檔案基本操作
#### 檔案存取方式

In [1]:
# open file
data = open('example.csv')
data

<_io.TextIOWrapper name='example.csv' mode='r' encoding='UTF-8'>

In [4]:
# open file (utf-8)
# readlines()：讀取整個文件所有行，保存於list內
data = open('example.csv', encoding = 'utf-8')
data.readlines()

['日期,成交股數,成交金額,成交筆數,發行量加權股價指數,漲跌點數\n',
 ' 104/01/02,"2,104,640,545","50,472,201,894","497,889","6,952.21",-119.87\n',
 ' 104/01/03,"2,640,781,030","64,138,886,194","623,192","7,053.38",101.17\n',
 ' 104/01/04,"2,983,756,821","75,845,629,353","728,417","7,082.97",29.59\n',
 ' 104/01/05,"3,062,757,248","76,850,752,698","737,780","7,130.86",47.89\n',
 ' 104/01/06,"3,314,147,435","88,101,921,548","823,810","7,120.51",-10.35\n',
 ' 104/01/09,"2,610,433,477","71,323,370,369","634,137","7,093.04",-27.47\n',
 ' 104/01/10,"3,595,611,551","97,168,542,017","869,327","7,178.87",85.83\n',
 ' 104/01/11,"3,322,390,467","88,786,671,892","802,539","7,188.21",9.34\n',
 ' 104/01/12,"2,969,248,375","78,947,910,460","731,328","7,186.58",-1.63\n',
 ' 104/01/13,"3,497,838,901","99,286,437,370","819,762","7,181.54",-5.04\n',
 ' 104/01/16,"3,184,795,667","76,842,611,338","719,725","7,103.62",-77.92\n',
 ' 104/01/17,"3,720,277,205","101,133,309,290","899,597","7,221.08",117.46\n',
 ' 104/01/18,"4,088,756,925","

In [5]:
# open file (utf-8)
# read(size)：從文件當前位置起讀取size個字元數量，若無參數，讀取至文件結束為止
data = open('example.csv', encoding = 'utf-8')
data.read()

'日期,成交股數,成交金額,成交筆數,發行量加權股價指數,漲跌點數\n 104/01/02,"2,104,640,545","50,472,201,894","497,889","6,952.21",-119.87\n 104/01/03,"2,640,781,030","64,138,886,194","623,192","7,053.38",101.17\n 104/01/04,"2,983,756,821","75,845,629,353","728,417","7,082.97",29.59\n 104/01/05,"3,062,757,248","76,850,752,698","737,780","7,130.86",47.89\n 104/01/06,"3,314,147,435","88,101,921,548","823,810","7,120.51",-10.35\n 104/01/09,"2,610,433,477","71,323,370,369","634,137","7,093.04",-27.47\n 104/01/10,"3,595,611,551","97,168,542,017","869,327","7,178.87",85.83\n 104/01/11,"3,322,390,467","88,786,671,892","802,539","7,188.21",9.34\n 104/01/12,"2,969,248,375","78,947,910,460","731,328","7,186.58",-1.63\n 104/01/13,"3,497,838,901","99,286,437,370","819,762","7,181.54",-5.04\n 104/01/16,"3,184,795,667","76,842,611,338","719,725","7,103.62",-77.92\n 104/01/17,"3,720,277,205","101,133,309,290","899,597","7,221.08",117.46\n 104/01/18,"4,088,756,925","113,988,641,382","1,020,420","7,233.69",12.61\n 104/01/30,"4,540,3

In [7]:
# open file (utf-8)
# readline()：讀取一行內容
data = open('example.csv', encoding = 'utf-8')
data.readline()

'日期,成交股數,成交金額,成交筆數,發行量加權股價指數,漲跌點數\n'

In [8]:
# create and write
# create a new one before write some words in file and close.
output = open('0610.txt', mode='w', encoding = 'utf-8')
output.write('Hello\n')
output.close()

In [2]:
# Practice
# https://od.cdc.gov.tw/eic/Age_County_Gender_19Cov.csv
cov = open('Age_County_Gender_19Cov.csv', encoding = 'utf-8')
cov.readlines()

['確定病名,發病年份,發病月份,縣市,鄉鎮,性別,是否為境外移入,年齡層,確定病例數\n',
 '嚴重特殊傳染性肺炎,2020,1,台中市,太平區,M,否,30-34,1\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,F,是,50-54,3\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,F,是,55-59,2\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,F,是,70+,2\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,M,是,20-24,1\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,M,是,40-44,1\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,M,是,50-54,1\n',
 '嚴重特殊傳染性肺炎,2020,1,空值,空值,M,是,55-59,1\n',
 '嚴重特殊傳染性肺炎,2020,1,南投縣,南投市,F,否,40-44,1\n',
 '嚴重特殊傳染性肺炎,2020,1,新北市,新莊區,F,否,20-24,1\n',
 '嚴重特殊傳染性肺炎,2020,1,新北市,林口區,F,否,65-69,1\n',
 '嚴重特殊傳染性肺炎,2020,1,新北市,新店區,M,否,45-49,1\n',
 '嚴重特殊傳染性肺炎,2020,1,新北市,新店區,M,否,50-54,1\n',
 '嚴重特殊傳染性肺炎,2020,1,彰化縣,和美鎮,M,否,50-54,1\n',
 '嚴重特殊傳染性肺炎,2020,1,彰化縣,彰化市,M,否,60-64,1\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,15-19,5\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,20-24,2\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,25-29,8\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,30-34,5\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,35-39,3\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,50-54,1\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,F,是,60-64,1\n',
 '嚴重特殊傳染性肺炎,2020,10,空值,空值,M,是

In [1]:
# 觀念強調
# list vs dict

colors = ['black', 'white', 'grey']
scores = {1 :'white', 0 :'black', 2 :'grey'}

# []：list, dict, numpy
print(colors[0])       # position == 0
print(scores[0])       # key == 0
print(scores.get(0))   # key == 0 (dict)

black
black
black


In [22]:
# Practice

no = 1
scores = dict()

while True:
    score = int(input('請輸入第 '+ str(no)+ ' 號的成績：(-1結束)' ))
    if score == -1: break;
    scores[no] = score  # 將取得的分數根據第幾次轉換成dict
    no += 1

# 將dict轉換成str寫入文字檔
file = open('score.txt', 'w', encoding = 'utf-8')
file.write(str(scores))

請輸入第 1 號的成績：(-1結束)99
請輸入第 2 號的成績：(-1結束)98
請輸入第 3 號的成績：(-1結束)87
請輸入第 4 號的成績：(-1結束)-1


21

In [23]:
# 承上，使用open必須在最後加入close，才可看見檔案內容
file.close()

In [25]:
file.write?
# Returns the number of characters written
# 上述練習執行後得出21，代表檔案內容字元數---> {1: 99, 2: 98, 3: 87}

In [1]:
# 尋找檔案位置 win, mac (magic command of jupyter notebook)
%pwd

'/Users/jean/Documents/GitHub/Python and AI Development/Day08_20210610_檔案存取與Numpy'

In [2]:
# read讀取上一範例中檔案並印出指定字元數（21）
result = open('score.txt', 'r', encoding = 'utf-8')
print(result.read(21))
result.close()

{1: 99, 2: 98, 3: 87}


In [3]:
# strip()：去除字串首尾空白
# lstrip()：去除字串左邊空白
# rstrip()：去除字串右邊空白
# startswith('字元')：第一個字元
' python '.strip(), \
' python '.lstrip(), \
' python '.rstrip(), \
' python '.startswith('p') # 第一個字元為空白才正確

('python', 'python ', ' python', False)

In [5]:
# Practice

f = open('data1.txt', 'r', encoding = 'utf-8')
result = list()
for line in f.readlines():
    line = line.strip()
    if not len(line) or line.startswith('#'): # 讀取資料列為空白或開頭為#就捨去，亦可寫成if len(line)=0。
        continue
    result.append(line)
result.sort()
print(result)
open('result-readlines.txt', 'w', encoding = 'utf-8').write('%s' % '\n'.join(result)) # 也可省略['%s' %]
# 將讀取後結果去除空白列或開頭為#的資料列，再寫出至新檔案

['Kuku L', 'Lucy T', 'Mia W']


19

In [10]:
not 0

True

In [11]:
# .join()用法sample

test = ['1', '2', '3']

print(','.join(test)) # 變更為'1,2,3'
print('\n'.join(test)) # 跳行
print(',\n'.join(test)) # 加入,跳行

1,2,3
1
2
3
1,
2,
3


## 檔案基本操作
#### CSV操作

In [17]:
# read csv file_1不加入編碼也可讀取

import csv

f = open('ExchangeRate@000000001601.csv', 'r')
for row in csv.reader(f):
    print(row)
f.close()

['\ufeffCurrency', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days']
['USD', 'Buying', '27.24500', '27.59500', '27.59000', '27.58900', '27.58500', '27.57600', '27.56700', '27.55700', '27.54800', 'Selling', '27.91500', '27.69500', '27.69600', '27.69500', '27.69400', '27.69300', '27.69100', '27.69000', '27.68900', '']
['HKD', 'Buying', '3.40500', '3.53100', '3.53100', '3.53000', '3.52900', '3.52900', '3.52800', '3.52700', '3.52500', 'Selling', '3.60900', '3.59100', '3.59100', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '']
['GBP', 'Buying', '37.83000', '38.84000', '38.83400', '38.82300', '38.81700', '38.81200', '38.79600', '38.78100', '38.76600', 'Selling', '39.95000', '39.24000', '39.24400', '39.25300', '39.24800'

In [23]:
# read csv file_2-1編碼轉換

import csv

f = open('ExchangeRate@000000001601.csv', 'r', encoding = 'big5')
for row in csv.reader(f):
    print(row)
f.close()

['嚜澧urrency', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days']
['USD', 'Buying', '27.24500', '27.59500', '27.59000', '27.58900', '27.58500', '27.57600', '27.56700', '27.55700', '27.54800', 'Selling', '27.91500', '27.69500', '27.69600', '27.69500', '27.69400', '27.69300', '27.69100', '27.69000', '27.68900', '']
['HKD', 'Buying', '3.40500', '3.53100', '3.53100', '3.53000', '3.52900', '3.52900', '3.52800', '3.52700', '3.52500', 'Selling', '3.60900', '3.59100', '3.59100', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '']
['GBP', 'Buying', '37.83000', '38.84000', '38.83400', '38.82300', '38.81700', '38.81200', '38.79600', '38.78100', '38.76600', 'Selling', '39.95000', '39.24000', '39.24400', '39.25300', '39.24800', '39

In [24]:
# read csv file_2-2編碼轉換

import csv

f = open('ExchangeRate@000000001601.csv', 'r', encoding = 'utf-8')
for row in csv.reader(f):
    print(row)
f.close()

['\ufeffCurrency', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days']
['USD', 'Buying', '27.24500', '27.59500', '27.59000', '27.58900', '27.58500', '27.57600', '27.56700', '27.55700', '27.54800', 'Selling', '27.91500', '27.69500', '27.69600', '27.69500', '27.69400', '27.69300', '27.69100', '27.69000', '27.68900', '']
['HKD', 'Buying', '3.40500', '3.53100', '3.53100', '3.53000', '3.52900', '3.52900', '3.52800', '3.52700', '3.52500', 'Selling', '3.60900', '3.59100', '3.59100', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '']
['GBP', 'Buying', '37.83000', '38.84000', '38.83400', '38.82300', '38.81700', '38.81200', '38.79600', '38.78100', '38.76600', 'Selling', '39.95000', '39.24000', '39.24400', '39.25300', '39.24800'

In [25]:
# read csv file_2-3編碼轉換

import csv

f = open('ExchangeRate@000000001601.csv', 'r', encoding = 'utf-8-sig') # -sig去除首字“\”
for row in csv.reader(f):
    print(row)
f.close()

['Currency', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days', 'Rate', 'Cash', 'Spot', 'Forward-10Days', 'Forward-30Days', 'Forward-60Days', 'Forward-90Days', 'Forward-120Days', 'Forward-150Days', 'Forward-180Days']
['USD', 'Buying', '27.24500', '27.59500', '27.59000', '27.58900', '27.58500', '27.57600', '27.56700', '27.55700', '27.54800', 'Selling', '27.91500', '27.69500', '27.69600', '27.69500', '27.69400', '27.69300', '27.69100', '27.69000', '27.68900', '']
['HKD', 'Buying', '3.40500', '3.53100', '3.53100', '3.53000', '3.52900', '3.52900', '3.52800', '3.52700', '3.52500', 'Selling', '3.60900', '3.59100', '3.59100', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '3.59200', '']
['GBP', 'Buying', '37.83000', '38.84000', '38.83400', '38.82300', '38.81700', '38.81200', '38.79600', '38.78100', '38.76600', 'Selling', '39.95000', '39.24000', '39.24400', '39.25300', '39.24800', '39.

In [26]:
# 補充：read csv file fast->Pandas!!!

import pandas as pd
pd.read_csv('ExchangeRate@000000001601.csv', index_col = False)

Currency    Rate      Cash     Spot  Forward-10Days  Forward-30Days  \
0       USD  Buying  27.24500  27.5950         27.5900         27.5890   
1       HKD  Buying   3.40500   3.5310          3.5310          3.5300   
2       GBP  Buying  37.83000  38.8400         38.8340         38.8230   
3       AUD  Buying  20.90000  21.1900         21.1870         21.1820   
4       CAD  Buying  22.28000  22.6800         22.6750         22.6650   
5       SGD  Buying  20.28000  20.7700         20.7650         20.7550   
6       CHF  Buying  30.00000  30.6800         30.6790         30.6760   
7       JPY  Buying   0.24200   0.2493          0.2493          0.2493   
8       ZAR  Buying   0.00000   1.9740          1.9710          1.9640   
9       SEK  Buying   2.95000   3.2900          3.2890          3.2880   
10      NZD  Buying  19.29000  19.6700         19.6650         19.6540   
11      THB  Buying   0.76060   0.8730          0.0000          0.0000   
12      PHP  Buying   0.50210   0.0000          0.0000          0.0000   
13      IDR  Buying   0.00163   0.0000          0.0000          0.0000   
14      EUR  Buying  32.76000  33.3800         33.3820         33.3870   
15      KRW  Buying   0.02300   0.0000          0.0000          0.0000   
16      VND  Buying   0.00083   0.0000          0.0000          0.0000   
17      MYR  Buying   5.60700   0.0000          0.0000          0.0000   
18      CNY  Buying   4.22000   4.2920          4.2882          4.2807   

    Forward-60Days  Forward-90Days  Forward-120Days  Forward-150Days  ...  \
0          27.5850         27.5760          27.5670          27.5570  ...   
1           3.5290          3.5290           3.5280           3.5270  ...   
2          38.8170         38.8120          38.7960          38.7810  ...   
3          21.1810         21.1810          21.1750          21.1680  ...   
4          22.6600         22.6570          22.6460          22.6360  ...   
5          20.7500         20.7460          20.7360          20.7270  ...   
6          30.6820         30.7220          30.7280          30.7340  ...   
7           0.2493          0.2493           0.2493           0.2493  ...   
8           1.9550          1.9460           1.9360           1.9260  ...   
9           3.2880          3.2880           3.2880           3.2870  ...   
10         19.6490         19.6440          19.6330          19.6230  ...   
11          0.0000          0.0000           0.0000           0.0000  ...   
12          0.0000          0.0000           0.0000           0.0000  ...   
13          0.0000          0.0000           0.0000           0.0000  ...   
14         33.3990         33.4150          33.4220          33.4280  ...   
15          0.0000          0.0000           0.0000           0.0000  ...   
16          0.0000          0.0000           0.0000           0.0000  ...   
17          0.0000          0.0000           0.0000           0.0000  ...   
18          4.2707          4.2605           4.2490           4.2376  ...   

     Rate.1    Cash.1   Spot.1  Forward-10Days.1  Forward-30Days.1  \
0   Selling  27.91500  27.6950           27.6960           27.6950   
1   Selling   3.60900   3.5910            3.5910            3.5920   
2   Selling  39.95000  39.2400           39.2440           39.2530   
3   Selling  21.68000  21.3900           21.3930           21.4000   
4   Selling  23.19000  22.8800           22.8830           22.8890   
5   Selling  21.19000  20.9500           20.9520           20.9570   
6   Selling  31.20000  30.9300           30.9450           30.9750   
7   Selling   0.25480   0.2533            0.2534            0.2535   
8   Selling   0.00000   2.0540            2.0520            2.0470   
9   Selling   3.47000   3.3900            3.3910            3.3930   
10  Selling  20.14000  19.8700           19.8730           19.8790   
11  Selling   0.95060   0.9130            0.0000            0.0000   
12  Selling   0.63510   0.0000            0.0000            0.0000   
1

In [28]:
# 補充：讀出csv檔後再轉出其他類型檔案

import pandas as pd
pd.read_csv('ExchangeRate@000000001601.csv', index_col = False).to_html('bank.html')
pd.read_csv('ExchangeRate@000000001601.csv', index_col = False).to_csv('bank.csv')
pd.read_csv('ExchangeRate@000000001601.csv', index_col = False).to_csv('bank_1.csv', index = False) # 去除第一行
# to_excel()
# to_html()
# to_csv()

## 檔案基本操作
#### json操作

In [2]:
# json資料操作
# dump(s)：將數據轉換成json格式檔案（變數）

import json

# dict變數
dict1 = {'Python':'好',
        'gjun':100,
       'Python-class':True,
       'ICQ':None}

# json變數
json2 = json.dumps(dict1, ensure_ascii = False) # 執行dumps時，加入ensure_ascii = False參數可避免亂碼產生
print('json變數:', json2)

json3 = json2.encode('utf-8')
print('json變數utf-8:', json3)

json變數: {"Python": "好", "gjun": 100, "Python-class": true, "ICQ": null}
json變數utf-8: b'{"Python": "\xe5\xa5\xbd", "gjun": 100, "Python-class": true, "ICQ": null}'


In [5]:
# Practice

import json

# dict變數
dict1 = {'Python':'好',
        'gjun':100,
       'Python-class':True,
       'ICQ':None}

# json變數
json2 = json.dumps(dict1, ensure_ascii = False)

# 開啟檔案，輸出dict1結果
with open('data0.json', 'w') as outfile:
    json.dump(dict1, outfile)

# 開啟檔案，輸出json變數結果
file = open('data1.json', 'w', encoding = 'utf-8')
file.write(json2)
file.close()

In [7]:
# json資料操作
# load(s)：從json字串的檔案(記憶體）中取出資料轉入Python的dict資料型態

import json

message = '{"python":"good", "gjun":100, "Python-class":true, "ICQ":null}'
json2 = json.loads(message) # 將json字串轉換成dict
print(json2, type(json2))

{'python': 'good', 'gjun': 100, 'Python-class': True, 'ICQ': None} <class 'dict'>


In [12]:
# Practice

with open('data0.json', 'r') as inputfile:
    message = inputfile.readlines() # 載入文字成list
print(message, type(message))

['{"Python": "\\u597d", "gjun": 100, "Python-class": true, "ICQ": null}'] <class 'list'>


In [10]:
# Practice

import json

with open('data0.json', 'r') as inputfile:
    json2 = json.load(inputfile, encoding = 'utf-8') # 載入json文字轉換成dict
print(json2, type(json2))

{'Python': '好', 'gjun': 100, 'Python-class': True, 'ICQ': None} <class 'dict'>


In [4]:
# Practice
# --> string + json format --> json.loads() --> python dict

# 姓名	身分證
# tom	A123456789
# ken	B112234567
# lewis	C123456789
# ada	D123456789
# Julia	E123456789
# jean	F234567891
# jim	X123456789
# annie	Y123456789

import json

data = '{"ALL":[{"姓名":"tom","身分證":"A123456789"},{"姓名":"ken","身分證":"B112234567"},{"姓名":"lewis","身分證":"C123456789"},{"姓名":"ada","身分證":"D123456789"},{"姓名":"Julia","身分證":"E123456789"},{"姓名":"jean","身分證":"F234567891"},{"姓名":"jim","身分證":"X123456789"},{"姓名":"annie","身分證":"Y123456789"}]}'
print(type(data))

json.loads(data)['ALL']

<class 'str'>


[{'姓名': 'tom', '身分證': 'A123456789'},
 {'姓名': 'ken', '身分證': 'B112234567'},
 {'姓名': 'lewis', '身分證': 'C123456789'},
 {'姓名': 'ada', '身分證': 'D123456789'},
 {'姓名': 'Julia', '身分證': 'E123456789'},
 {'姓名': 'jean', '身分證': 'F234567891'},
 {'姓名': 'jim', '身分證': 'X123456789'},
 {'姓名': 'annie', '身分證': 'Y123456789'}]

## 檔案進階操作

In [1]:
# https://docs.python.org/3/library/exceptions.html

try:
    f = open('ooxx.csv','r')
except FileNotFoundError:
    print('FileNotFoundError')
except PermissionError:
    print('PermissionError')
except:
    print('ERROR')

FileNotFoundError


In [3]:
# with --> open & close自動處理
# 離開with區塊時檔案將會自動進行close()動作

with open('score.txt') as myfile:
    data = myfile.readlines()
data

['{1: 99, 2: 98, 3: 87}']

In [4]:
# 檔案存取仍有可能產生IO例外

try:
    with open('scores.txt', encoding = "utf-8-sig" ) as myfile:
        data = myfile.readlines() 
    print(data)
except:
    print('NO_FILE_FOUND')

NO_FILE_FOUND


In [5]:
# 強化編碼會有 --> \ufeff
try:
    with open('ExchangeRate@000000001601.csv', encoding = "utf-8" ) as myfile:
        data = myfile.readlines() 
    print(data)
except:
    print('NO_FILE_FOUND')

['\ufeffCurrency,Rate,Cash,Spot,Forward-10Days,Forward-30Days,Forward-60Days,Forward-90Days,Forward-120Days,Forward-150Days,Forward-180Days,Rate,Cash,Spot,Forward-10Days,Forward-30Days,Forward-60Days,Forward-90Days,Forward-120Days,Forward-150Days,Forward-180Days\n', 'USD,Buying,27.24500,27.59500,27.59000,27.58900,27.58500,27.57600,27.56700,27.55700,27.54800,Selling,27.91500,27.69500,27.69600,27.69500,27.69400,27.69300,27.69100,27.69000,27.68900,\n', 'HKD,Buying,3.40500,3.53100,3.53100,3.53000,3.52900,3.52900,3.52800,3.52700,3.52500,Selling,3.60900,3.59100,3.59100,3.59200,3.59200,3.59200,3.59200,3.59200,3.59200,\n', 'GBP,Buying,37.83000,38.84000,38.83400,38.82300,38.81700,38.81200,38.79600,38.78100,38.76600,Selling,39.95000,39.24000,39.24400,39.25300,39.24800,39.24400,39.24300,39.24200,39.24100,\n', 'AUD,Buying,20.90000,21.19000,21.18700,21.18200,21.18100,21.18100,21.17500,21.16800,21.16000,Selling,21.68000,21.39000,21.39300,21.40000,21.39900,21.39900,21.40100,21.40200,21.40200,\n', 'CA

In [6]:
# 承上，去除強化編碼加入sig
try:
    with open('ExchangeRate@000000001601.csv', encoding = "utf-8-sig" ) as myfile:
        data = myfile.readlines() 
    print(data)
except:
    print('NO_FILE_FOUND')

['Currency,Rate,Cash,Spot,Forward-10Days,Forward-30Days,Forward-60Days,Forward-90Days,Forward-120Days,Forward-150Days,Forward-180Days,Rate,Cash,Spot,Forward-10Days,Forward-30Days,Forward-60Days,Forward-90Days,Forward-120Days,Forward-150Days,Forward-180Days\n', 'USD,Buying,27.24500,27.59500,27.59000,27.58900,27.58500,27.57600,27.56700,27.55700,27.54800,Selling,27.91500,27.69500,27.69600,27.69500,27.69400,27.69300,27.69100,27.69000,27.68900,\n', 'HKD,Buying,3.40500,3.53100,3.53100,3.53000,3.52900,3.52900,3.52800,3.52700,3.52500,Selling,3.60900,3.59100,3.59100,3.59200,3.59200,3.59200,3.59200,3.59200,3.59200,\n', 'GBP,Buying,37.83000,38.84000,38.83400,38.82300,38.81700,38.81200,38.79600,38.78100,38.76600,Selling,39.95000,39.24000,39.24400,39.25300,39.24800,39.24400,39.24300,39.24200,39.24100,\n', 'AUD,Buying,20.90000,21.19000,21.18700,21.18200,21.18100,21.18100,21.17500,21.16800,21.16000,Selling,21.68000,21.39000,21.39300,21.40000,21.39900,21.39900,21.40100,21.40200,21.40200,\n', 'CAD,Buyi

In [7]:
# Practice
# 如何轉換scores --> names?

scores = { 0:'Jean',  1:'Lucy', 2:'Kuku'}
names = {'Jean':0 , 'Lucy':1 , 'Kuku':2}

[s for s in scores.items()]

[(0, 'Jean'), (1, 'Lucy'), (2, 'Kuku')]

In [8]:
# Practice
# 如何轉換scores --> names?
dict([ (v,k) for (k,v) in scores.items() ])

{'Jean': 0, 'Lucy': 1, 'Kuku': 2}

## Numpy

In [12]:
# Numpy：陣列類似list，但當中所有元素必須是相同資料型態，如int、float、string
# List：每一個元素可以不同資料型態，如int、float、string
# List vs Numpy

# List
scores = [12, 46, 33, 68, 51]
(scores, type(scores))

([12, 46, 33, 68, 51], list)

In [13]:
# Numpy
import numpy as np
np.array(scores), type(np.array(scores))

(array([12, 46, 33, 68, 51]), numpy.ndarray)

In [16]:
# 將以上列表中的分數再加上30分
# List無法“直接”使用算術運算工具（+, -, *, /）

# List
# scores + 40 ---> 無法直接運算
[s + 40 for s in scores]

[52, 86, 73, 108, 91]

In [15]:
# 承上，Numpy提供更有效率計算與多維運算工具（批次運算）

# Numpy
import numpy as np
np.array(scores) + 40

array([ 52,  86,  73, 108,  91])

In [22]:
# Practice_List操作

a = [1, 3, 5, 7, 9]
print(a[2:4])

b = [
     [1, 3, 5, 7, 9],  #0
     [2, 4, 6, 8, 10]  #1
    ]
print(b[0])
print(b[1][2:4])

c = [1, 3, 5, 7, 9]
d = [3, 5, 6, 7, 9]
f = c + d
print(f)

[5, 7]
[1, 3, 5, 7, 9]
[6, 8]
[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


In [23]:
# Practice_Numpy操作

import numpy as np
a = np.array([1, 3, 5, 7, 9])
print(a[2:4])

b = np.array([
     [1, 3, 5, 7, 9],  #0
     [2, 4, 6, 8, 10]  #1
    ])
print(b[0])
print(b[1][2:4])

c = np.array([1, 3, 5, 7, 9])
d = np.array([3, 5, 6, 7, 9])
f = c + d
print(f)

[5 7]
[1 3 5 7 9]
[6 8]
[ 4  8 11 14 18]


In [ ]:
# important concept
# Numpy為每個科學Python應用程序或模組的核心，提供以向量化形式的快速N-d陣列類型可供操作。
# 0-d(scalar)|1-d(list)|2-d(Table Excel)|3-d(image)

In [24]:
# shape指令可得知陣列(rank)形狀，亦可稱作張量(tensor) -->維度
# Numpy陣列稱為ndarray，透過array方法將list轉換為ndarray。

# 0 - 維度
import numpy as np
np.array(100).shape

()

In [25]:
# 1 - 維度
import numpy as np
np.array([100, 200, 300]).shape

(3,)

In [26]:
# 2 - 維度（上下, 左右）
import numpy as np
np.array([[100, 200, 300],
          [100, 200, 300],
          [100, 200, 300],
          [100, 200, 300]]).shape

(4, 3)

In [27]:
# 3 - 維度（上下, 左右, 前後）
import numpy as np
np.array([
          [
              [100, 200, 300],
              [100, 200, 300],
              [100, 200, 300],
              [100, 200, 300]
          ],
          [
              [100, 200, 300],
              [100, 200, 300],
              [100, 200, 300],
              [100, 200, 300]
          ]
          ]).shape

(2, 4, 3)

In [28]:
# Practice

import numpy as np
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
print(c)
print("---------------")
c = a - b
print(c)
print("---------------")
print(type(c))

[ 4  8 11 14 18]
---------------
[-2 -2 -1  0  0]
---------------
<class 'numpy.ndarray'>


## HW：檔案存取

In [6]:
# 請至政府資料開放平台下載‘澎湖縣西嶼鄉公所對民間團體補(捐)助經費明細表‘
# 讀取前三個columns資料

import csv

data = open('HW8__Data.csv', 'r', encoding = 'utf-8-sig')
for row in csv.DictReader(data, ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']):
    print(row['a'], row['b'], row['c'])
data.close()

工作計畫_科目名稱 補助事項或用途 補助對象
農產推廣--農產推廣 辦理澎湖縣各界慶祝105年農民節大會活動經費 澎湖縣農會
社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉外垵社區發展協會
社區發展--社區發展 105年度垃圾分類暨資源回收宣導 澎湖縣西嶼鄉大池社區發展協會
社區發展--社區發展 105年年關交通安全宣導活動暨鄰長聯誼餐敘 澎湖縣西嶼鄉橫礁社區發展協會
社區發展--社區發展 年節防詐騙及安全宣導計畫 澎湖縣西嶼鄉二崁社區發展協會
社區發展--社區發展 年關慢性病防治宣導暨社區志工及老人聯誼餐敘 澎湖縣西嶼鄉橫礁社區發展協會
社區發展--社區發展 105年防詐騙住宅防竊宣導活動 澎湖縣西嶼鄉赤馬社區發展協會
社區發展--社區發展 105年垃圾分類暨資源回收宣導 澎湖縣西嶼鄉小門社區發展協會
社區發展--社區發展 內垵擊鼓表演暨村鄰長聯誼活動 澎湖縣西嶼鄉內垵社區發展協會
社區發展--社區發展 歡慶元宵聯歡晚會 澎湖縣西嶼鄉小門社區發展協會
社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉大池社區發展協會
社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉赤馬社區發展協會
社區發展--社區發展 105年池府王爺平安繞境活動 澎湖縣西嶼鄉內垵社區發展協會
社區發展--社區發展 105年平安燒境祈福活動 澎湖縣西嶼鄉赤馬社區發展協會
社區發展--社區發展 105年老人關懷據點-點心品嚐活動 澎湖縣西嶼鄉內垵社區發展協會
社區發展--社區發展 2016丙申年金猴獻瑞慶元宵民俗活動 澎湖縣西嶼鄉外垵社區發展協會
社區發展--社區發展 105年歡慶元宵猜燈謎晚會活動 澎湖縣西嶼鄉內垵社區發展協會
社區發展--社區發展 105年度聯合社區計畫 澎湖縣西嶼鄉竹灣社區發展協會
社區發展--社區發展 召開第六屆第一次會員大會暨春節聯誼活動費 澎湖視障協進會
社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉橫礁社區發展協會
社區發展--社區發展 第1次社區成長教室 澎湖縣西嶼鄉竹灣社區發展協會
社區發展--社區發展 福德宮鎮符遶境祈福活動 澎湖縣西嶼鄉池西社區發展協會
社區發展--社區發展 晨泳協會辦理晨泳安全講習活動 澎湖縣西嶼晨泳協會
社區發展--社區發展 辦理105年戒煙宣導暨歌唱聯誼活動 澎湖縣內塹土風舞協會
社區發展--社區發展 第1次社區

In [7]:
# 使用pandas

import pandas as pd

pd.read_csv('HW8__Data.csv').iloc[ : , :3] 
# iloc = index Location

工作計畫_科目名稱                 補助事項或用途            補助對象
0    農產推廣--農產推廣  辦理澎湖縣各界慶祝105年農民節大會活動經費           澎湖縣農會
1    社區發展--社區發展               第1次社區成長教室  澎湖縣西嶼鄉外垵社區發展協會
2    社區發展--社區發展        105年度垃圾分類暨資源回收宣導  澎湖縣西嶼鄉大池社區發展協會
3    社區發展--社區發展   105年年關交通安全宣導活動暨鄰長聯誼餐敘  澎湖縣西嶼鄉橫礁社區發展協會
4    社區發展--社區發展            年節防詐騙及安全宣導計畫  澎湖縣西嶼鄉二崁社區發展協會
..          ...                     ...             ...
121  社區發展--社區發展        補助105年下半年社區成果維護費  澎湖縣西嶼鄉赤馬社區發展協會
122  社區發展--社區發展        補助105年下半年社區成果維護費  澎湖縣西嶼鄉竹灣社區發展協會
123  社區發展--社區發展        補助105年下半年社區成果維護費  澎湖縣西嶼鄉橫礁社區發展協會
124  社區發展--社區發展        補辦理105年莫蘭蒂風災修復工程  澎湖縣西嶼鄉竹灣社區發展協會
125          合計                     NaN             NaN

[126 rows x 3 columns]