## Pandas資料探索

In [10]:
# Pandas觀念強調

data1 = {"name" : ["中正區", "板橋區", "桃園區", "北屯區",
                   "安南區", "三民區", "大安區", "永和區",
                   "八德區", "前鎮區", "鳳山區",
                   "信義區", "新店區"],
         "population" : [159598, 551452, 441287, 275207,
                         192327, 343203, 309835, 222531,
                         198473, 189623, 359125,
                         225561, 302070],
         "city" : ["台北市", "新北市", "桃園市", "台中市",
                   "台南市", "高雄市", "台北市", "新北市",
                   "桃園市", "高雄市", "高雄市",
                   "台北市", "新北市"]}

data2 = ["first", "second", "third", "fourth", "fifth",
         "sixth", "seventh", "eigth", "ninth", "tenth",
         "eleventh", "twelvth", "thirteenth"]

import pandas as pd

df = pd.DataFrame(data1) # DataFrame：header, row(s), column(s), index
df[:4]                   # [[column, column, column]] = DataFrame[[]] = N * Series[]

name  population city
0  中正區      159598  台北市
1  板橋區      551452  新北市
2  桃園區      441287  桃園市
3  北屯區      275207  台中市

In [2]:
df['population'] # 上下全部、左右使用名稱篩選 [Series]

0     159598
1     551452
2     441287
3     275207
4     192327
5     343203
6     309835
7     222531
8     198473
9     189623
10    359125
11    225561
12    302070
Name: population, dtype: int64

In [3]:
df[['population']] # 上下全部、左右使用名稱篩選 [[DataFrame]]

population
0       159598
1       551452
2       441287
3       275207
4       192327
5       343203
6       309835
7       222531
8       198473
9       189623
10      359125
11      225561
12      302070

In [4]:
df[['population', 'city']] # 上下全部、左右使用名稱篩選 [['', '']]

population city
0       159598  台北市
1       551452  新北市
2       441287  桃園市
3       275207  台中市
4       192327  台南市
5       343203  高雄市
6       309835  台北市
7       222531  新北市
8       198473  桃園市
9       189623  高雄市
10      359125  高雄市
11      225561  台北市
12      302070  新北市

In [5]:
df.iloc[0:3, 0:2] # .iloc[索引的位置] (不包含尾)

name  population
0  中正區      159598
1  板橋區      551452
2  桃園區      441287

In [6]:
df.loc[0:3, ['name', 'population']] # .loc[索引值] (包含尾)

name  population
0  中正區      159598
1  板橋區      551452
2  桃園區      441287
3  北屯區      275207

In [7]:
# Exam
# 取後三筆的population、city資料

data1 = {"name" : ["中正區", "板橋區", "桃園區", "北屯區",
                   "安南區", "三民區", "大安區", "永和區",
                   "八德區", "前鎮區", "鳳山區",
                   "信義區", "新店區"],
         "population" : [159598, 551452, 441287, 275207,
                         192327, 343203, 309835, 222531,
                         198473, 189623, 359125,
                         225561, 302070],
         "city" : ["台北市", "新北市", "桃園市", "台中市",
                   "台南市", "高雄市", "台北市", "新北市",
                   "桃園市", "高雄市", "高雄市",
                   "台北市", "新北市"]}

import pandas as pd

df = pd.DataFrame(data1)

#df.loc[10:, ['population', 'city']]
#df.iloc[-3:, 1:3]
#df.iloc[-3:, 1:]
#df.iloc[-3:, [1,2]]
df[-3:][['population', 'city']] # 補充：利用numpy方式取出後三筆的DataFrame，再切割左右欄位

population city
10      359125  高雄市
11      225561  台北市
12      302070  新北市

In [8]:
# 承上，取出前三筆和後三筆的population、city資料

df.iloc[[0, 1, 2, -3, -2, -1], 1:]

population city
0       159598  台北市
1       551452  新北市
2       441287  桃園市
10      359125  高雄市
11      225561  台北市
12      302070  新北市

In [12]:
# Practice

import pandas as pd

df = pd.DataFrame(data1, columns = ["name", "city", "population"]) #, index = data2實際上很少用此資料當索引
print(df[["city"]])
print("-------")
print(df[["city", "name"]])
print("-------")
print(df[2:5][["city", "name"]])
print("-------")
list1 = ["city", "name"]
print(df[3:6][list1])

   city
0   台北市
1   新北市
2   桃園市
3   台中市
4   台南市
5   高雄市
6   台北市
7   新北市
8   桃園市
9   高雄市
10  高雄市
11  台北市
12  新北市
-------
   city name
0   台北市  中正區
1   新北市  板橋區
2   桃園市  桃園區
3   台中市  北屯區
4   台南市  安南區
5   高雄市  三民區
6   台北市  大安區
7   新北市  永和區
8   桃園市  八德區
9   高雄市  前鎮區
10  高雄市  鳳山區
11  台北市  信義區
12  新北市  新店區
-------
  city name
2  桃園市  桃園區
3  台中市  北屯區
4  台南市  安南區
-------
  city name
3  台中市  北屯區
4  台南市  安南區
5  高雄市  三民區


## Numpy與Pandas寫法差異

In [13]:
# 依據網址下載資料

import pandas as pd

fruits = pd.read_csv('https://goo.gl/DOw6pe')
fruits

Apples  Bananas  Cherries
0       2        1         4
1       7        5         3
2      12        8         6

In [14]:
# 承上，列出第一筆後的資料
fruits[1:]

Apples  Bananas  Cherries
1       7        5         3
2      12        8         6

In [15]:
# 承上，列出第一筆前的資料
fruits[:1]

Apples  Bananas  Cherries
0       2        1         4

In [20]:
# exam，如何列出第一筆資料
# numpy寫法
fruits[1:2]

Apples  Bananas  Cherries
1       7        5         3

In [24]:
# pandas寫法（此型態為Series）
print(fruits.iloc[1])
print(type(fruits.iloc[1]))

Apples      7
Bananas     5
Cherries    3
Name: 1, dtype: int64
<class 'pandas.core.series.Series'>


In [25]:
# 等同上述寫法（型態一樣為Series）
print(fruits.iloc[1, :])
print(type(fruits.iloc[1, :]))

Apples      7
Bananas     5
Cherries    3
Name: 1, dtype: int64
<class 'pandas.core.series.Series'>


In [26]:
# pandas寫法（此型態為DataFrame）
print(fruits.iloc[[1]])
print(type(fruits.iloc[[1]]))

   Apples  Bananas  Cherries
1       7        5         3
<class 'pandas.core.frame.DataFrame'>


In [27]:
# 等同上述寫法（型態一樣為DataFrame）
print(fruits.iloc[[1], :])
print(type(fruits.iloc[[1], :]))

   Apples  Bananas  Cherries
1       7        5         3
<class 'pandas.core.frame.DataFrame'>


In [30]:
## Pandas，但為Numpy寫法（型態為DataFrame）
fruits.iloc[1:2, :]

Apples  Bananas  Cherries
1       7        5         3

In [35]:
# 改為.loc（型態為Series）
print(fruits.loc[1])
print(type(fruits.loc[1]))

Apples      7
Bananas     5
Cherries    3
Name: 1, dtype: int64
<class 'pandas.core.series.Series'>


In [36]:
# 改為.loc（型態為DataFrame）
print(fruits.loc[[1]])
print(type(fruits.loc[[1]]))

   Apples  Bananas  Cherries
1       7        5         3
<class 'pandas.core.frame.DataFrame'>


In [37]:
# 左右切割（型態為Series）
fruits['Bananas']

0    1
1    5
2    8
Name: Bananas, dtype: int64

In [38]:
# 左右切割（型態為DataFrame）
fruits[['Bananas']]

Bananas
0        1
1        5
2        8

In [41]:
# 將此錯誤程式碼改為正確的 ---> fruits[:, 'Bananas']
fruits.loc[:, ['Bananas']]

Bananas
0        1
1        5
2        8

In [1]:
# 產生20210101 - 20210103的資料

import pandas as pd
pd.date_range('20210101', '20210103')

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03'], dtype='datetime64[ns]', freq='D')

In [2]:
# 使用日期當成DataFrame的索引（日期區間）

import pandas as pd

fruitsdt = pd.read_csv('https://goo.gl/DOw6pe')
fruitsdt.index = pd.date_range('20210101', '20210103')
fruitsdt

Apples  Bananas  Cherries
2021-01-01       2        1         4
2021-01-02       7        5         3
2021-01-03      12        8         6

In [4]:
# 承上，使用iloc

import pandas as pd

fruitsdt = pd.read_csv('http://goo.gl/DOw6pe')
fruitsdt.index = pd.date_range('20210101', '20210103')
fruitsdt.iloc[0:2]

Apples  Bananas  Cherries
2021-01-01       2        1         4
2021-01-02       7        5         3

In [5]:
# 承上，使用loc

import pandas as pd

fruitsdt = pd.read_csv('http://goo.gl/DOw6pe')
fruitsdt.index = pd.date_range('20210101', '20210103')
fruitsdt.loc['2021-01-01':'2021-01-02']

Apples  Bananas  Cherries
2021-01-01       2        1         4
2021-01-02       7        5         3

In [7]:
# 產生六天資料

pd.date_range('20180516', periods = 6)

DatetimeIndex(['2018-05-16', '2018-05-17', '2018-05-18', '2018-05-19',
               '2018-05-20', '2018-05-21'],
              dtype='datetime64[ns]', freq='D')

In [8]:
# Practice-1（以下印出各種結果）

import pandas as pd
import numpy as np

dates = pd.date_range('20180516', periods=6)
df = pd.DataFrame(np.arange(24).reshape(6,4),
                 index = dates,
                 columns = ['a','b','c','d'])
df

a   b   c   d
2018-05-16   0   1   2   3
2018-05-17   4   5   6   7
2018-05-18   8   9  10  11
2018-05-19  12  13  14  15
2018-05-20  16  17  18  19
2018-05-21  20  21  22  23

In [9]:
df.loc[:,['a','b']]

a   b
2018-05-16   0   1
2018-05-17   4   5
2018-05-18   8   9
2018-05-19  12  13
2018-05-20  16  17
2018-05-21  20  21

In [10]:
df.loc['20180517':, ['a','b']]

a   b
2018-05-17   4   5
2018-05-18   8   9
2018-05-19  12  13
2018-05-20  16  17
2018-05-21  20  21

In [11]:
df.loc['20180517':, ['b']]

b
2018-05-17   5
2018-05-18   9
2018-05-19  13
2018-05-20  17
2018-05-21  21

In [12]:
df.loc['20180518':'20180520', 'b':'d'] 

b   c   d
2018-05-18   9  10  11
2018-05-19  13  14  15
2018-05-20  17  18  19

In [14]:
print(df['b'])
print("------------")
print(df.b) # 如果有空白或關鍵字，使用”.“可能會有錯誤
print("------------")
print(df.iloc[0:3]) # 類似.iloc
print("------------")
print(df.loc['20180516':'20180518']) # 等同.loc

2018-05-16     1
2018-05-17     5
2018-05-18     9
2018-05-19    13
2018-05-20    17
2018-05-21    21
Freq: D, Name: b, dtype: int64
------------
2018-05-16     1
2018-05-17     5
2018-05-18     9
2018-05-19    13
2018-05-20    17
2018-05-21    21
Freq: D, Name: b, dtype: int64
------------
            a  b   c   d
2018-05-16  0  1   2   3
2018-05-17  4  5   6   7
2018-05-18  8  9  10  11
------------
            a  b   c   d
2018-05-16  0  1   2   3
2018-05-17  4  5   6   7
2018-05-18  8  9  10  11


In [16]:
# Practice-2（以下印出各種結果）

import pandas as pd

groups = ["Python", "Django", "Sqlite", "Numpy", "Security", "Pandas"]
numbers = [59, 9, 19, 14, 6, 77]
group_dict = {
            "groups": groups,
            "numbers": numbers
             }
df1 = pd.DataFrame(group_dict)
df1

groups  numbers
0    Python       59
1    Django        9
2    Sqlite       19
3     Numpy       14
4  Security        6
5    Pandas       77

In [42]:
# practice-2結果的列表（以下個別印出結果）

df1.iloc[0:1, 1]
df1.iloc[0:1, :]
df1.iloc[ : , 1]
df1["numbers"]
df1.numbers
df1.iloc[2]
df1.iloc[[2]]

groups  numbers
2  Sqlite       19

In [17]:
df1.iloc[0:1, 1]

0    59
Name: numbers, dtype: int64

In [18]:
df1.iloc[0:1, :]

groups  numbers
0  Python       59

In [19]:
df1.iloc[:, 1]

0    59
1     9
2    19
3    14
4     6
5    77
Name: numbers, dtype: int64

In [21]:
df1['numbers']

0    59
1     9
2    19
3    14
4     6
5    77
Name: numbers, dtype: int64

In [22]:
df1.numbers

0    59
1     9
2    19
3    14
4     6
5    77
Name: numbers, dtype: int64

In [23]:
df1.iloc[2]

groups     Sqlite
numbers        19
Name: 2, dtype: object

In [24]:
df1.iloc[[2]]

groups  numbers
2  Sqlite       19

In [25]:
# Practice-3

import pandas as pd

marketing=pd.read_csv("https://goo.gl/6A6Qe2")
marketing

ID  Views  Clicks
a   1   1000     300
b   2   1200     800
c   3    800     500

In [43]:
# practice-3結果的列表（以下個別印出結果）

marketing.loc[['a','c'], ['Views','Clicks']]
marketing.loc['b' , :]
marketing.loc[['b']]
marketing.loc[['a', 'c']]
marketing.loc[:, ['ID', 'Clicks']]
marketing.iloc[:, [0, 2]]
marketing.iloc[0:2, [0, 2]]

ID  Clicks
a   1     300
b   2     800

In [26]:
marketing.loc[['a', 'c'], ['Views', 'Clicks']]

Views  Clicks
a   1000     300
c    800     500

In [27]:
marketing.loc['b', : ]

ID           2
Views     1200
Clicks     800
Name: b, dtype: int64

In [28]:
marketing.loc[['b']]

ID  Views  Clicks
b   2   1200     800

In [29]:
marketing.loc[['a', 'c']]

ID  Views  Clicks
a   1   1000     300
c   3    800     500

In [30]:
marketing.loc[:, ['ID', 'Clicks']]

ID  Clicks
a   1     300
b   2     800
c   3     500

In [31]:
marketing.iloc[:, [0, 2]]

ID  Clicks
a   1     300
b   2     800
c   3     500

In [32]:
marketing.iloc[0:2, [0, 2]]

ID  Clicks
a   1     300
b   2     800

In [33]:
# Practice-4

import pandas as pd
import numpy as np

dates = pd.date_range('20180516',periods=6)
df = pd.DataFrame(np.arange(24).reshape(6,4), index = dates, columns = ['a', 'b', 'c', 'd'])
df

a   b   c   d
2018-05-16   0   1   2   3
2018-05-17   4   5   6   7
2018-05-18   8   9  10  11
2018-05-19  12  13  14  15
2018-05-20  16  17  18  19
2018-05-21  20  21  22  23

In [40]:
# practice-4結果的列表（以下個別印出結果）

df.iloc[[3]]
df.iloc[3        , 1  ] # row = 3, column = 1
df.iloc[[3, 1]   ,  : ] # row = 3, 1
df.iloc[[3, 1]        ] # row = 3, 1
df.iloc[3:5      , 1:3] # row = 3, 4, column = 1, 2
df.iloc[[1, 3, 5], 1:3] # row = 1, 3, 5, column = 1, 2

b   c
2018-05-17   5   6
2018-05-19  13  14
2018-05-21  21  22

In [34]:
df.iloc[[3]]

a   b   c   d
2018-05-19  12  13  14  15

In [35]:
df.iloc[3, 1] # row = 3, column = 1

13

In [36]:
df.iloc[[3, 1] , : ] # row = 3, 1

a   b   c   d
2018-05-19  12  13  14  15
2018-05-17   4   5   6   7

In [37]:
df.iloc[[3, 1]] # row = 3, 1

a   b   c   d
2018-05-19  12  13  14  15
2018-05-17   4   5   6   7

In [38]:
df.iloc[3:5, 1:3] # row = 3, 4, column = 1, 2

b   c
2018-05-19  13  14
2018-05-20  17  18

In [41]:
df.iloc[[1, 3, 5], 1:3] # row = 1, 3, 5, column = 1, 2

b   c
2018-05-17   5   6
2018-05-19  13  14
2018-05-21  21  22

## 陣列合併與拆解

In [1]:
import pandas as pd
fruits = pd.read_csv('https://goo.gl/DOw6pe')
fruits

Apples  Bananas  Cherries
0       2        1         4
1       7        5         3
2      12        8         6

In [2]:
# pandas --> numpy
data = fruits.values
data

array([[ 2,  1,  4],
       [ 7,  5,  3],
       [12,  8,  6]])

## row的切割與合併

In [3]:
# np.vsplit()：可指定要切割的數量（水平切割後，結果顯示為垂直方式）

import numpy as np
np.vsplit(data, 3)

[array([[2, 1, 4]]), array([[7, 5, 3]]), array([[12,  8,  6]])]

In [4]:
# Practice

import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.vsplit(a, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [6]:
b = np.arange(12, 24).reshape(3, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
# np.vstack(tup)：進行合併

np.vstack( (a, b) )  # (動  (tuple)  作)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## column的切割與合併

In [8]:
# Practice

import numpy as np
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# np.hsplit()：可指定要切割的數量（垂直切割後，結果顯示為水平方式）

np.hsplit(a, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [10]:
b = np.arange(12, 24).reshape(3, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
# np.hstack(tup)：進行合併

np.hstack( (a, b) ) # 最後結果顯示是水平方式

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

## 可選擇行列的切割與合併

In [12]:
# np.split()：代表切割的動作
# ->若axis = 0代表row切割，等同vsplit
# ->若axis = 1代表column切割，等同hsplit

import numpy as np
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
np.split(a, 3, axis = 0) # axis = 0 上下

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [14]:
np.split(a, 4, axis = 1) # axis = 1 左右

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [15]:
b = np.arange(12, 24).reshape(3, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
# np.concatenate()：代表合併動作
# ->若axis = 0代表row合併，等同vstack
# ->若axis = 1代表column合併，等同hstack
np.concatenate( (a, b), axis = 1 )

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# numpy, pandas : 先看 上下(axis=0)，再看 左右(axis=1)
# matplotlib    : 先看 x 左右，再看 y 上下

## 不等量切割

In [17]:
a # 3*4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.array_split(a, 3, axis = 1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

## HW：檔案讀取查詢

In [1]:
# 可從政府資料開放平台取得資料
# 請載入CSV檔案內容並設定查詢（例如是否可以輸入郵遞區號列出所有的派出所）？

In [14]:
!ls -rtl *.csv

-rw-r--r--@ 1 jean  staff  196000 Jun  3 19:40 HW11__Data.csv


In [15]:
import pandas as pd

df = pd.read_csv('HW11__Data.csv')
df[:3]

中文單位名稱                          英文單位名稱  郵遞區號                地址  \
0  臺北市政府警察局   Taipei City Police Department   100     臺北市中正區延平南路96號   
1      中山分局              Zhongshan Precinct   104    臺北市中山區中山北路2段1號   
2    中山一派出所  Zhongshan First Police Station   104  臺北市中山區中山北路1段110號   

            電話      POINT_X      POINT_Y  
0  02 23313561  301442.6468  2770733.688  
1  02 25412491  302750.6974  2771704.464  
2  02 25519321  302613.5457  2771415.780

In [7]:
postcode = input('郵遞區號')
print(postcode)

郵遞區號104
104


In [16]:
# 需求就是根據輸入郵遞區號找出對應資料列
# list comprehension
data = df.values.tolist()
data[:2]

[['臺北市政府警察局',
  'Taipei City Police Department',
  100,
  '臺北市中正區延平南路96號',
  '02 23313561',
  301442.6468,
  2770733.688],
 ['中山分局',
  'Zhongshan Precinct',
  104,
  '臺北市中山區中山北路2段1號',
  '02 25412491',
  302750.6974,
  2771704.464]]

In [18]:
# list comprehension

postcode = int(input('請輸入郵遞區號'))
[d for d in data if d[2] == postcode]

請輸入郵遞區號104


[['中山分局',
  'Zhongshan Precinct',
  104,
  '臺北市中山區中山北路2段1號',
  '02 25412491',
  302750.6974,
  2771704.464],
 ['中山一派出所',
  'Zhongshan First Police Station',
  104,
  '臺北市中山區中山北路1段110號',
  '02 25519321',
  302613.5457,
  2771415.78],
 ['中山二派出所',
  'Zhongshan Second Police Station',
  104,
  '臺北市中山區中山北路2段90號',
  '02 25517771',
  302727.2356,
  2772263.722],
 ['圓山派出所',
  'Yuanshan Police Staticn',
  104,
  '臺北市中山區中山北路3段62號',
  '02 25969433',
  302834.9838,
  2773933.985],
 ['長春路派出所',
  'Changchun Rd. Police Station',
  104,
  '臺北市中山區長春路206號',
  '02 25062289',
  304083.3089,
  2771936.628],
 ['長安東路派出所',
  'Changan E. Rd. Police Station',
  104,
  '臺北市中山區長安東路2段165號',
  '02 27735207',
  304542.2421,
  2771254.798],
 ['民權一派出所',
  'Minquan First Police Station',
  104,
  '臺北市中山區新生北路2段127之1號',
  '02 25314672',
  303266.0302,
  2772517.502],
 ['建國路派出所',
  'Jianguo Police Station',
  104,
  '臺北市中山區民族東路284號',
  '02 25099774',
  304074.2363,
  2773416.496],
 ['大直派出所',
  'Dazhi Police Station',
  10

In [20]:
# DataFrame subset

postcode = int(input('請輸入郵遞區號'))
df[df['郵遞區號'] == postcode]

請輸入郵遞區號104


中文單位名稱                           英文單位名稱  郵遞區號                  地址  \
1     中山分局               Zhongshan Precinct   104      臺北市中山區中山北路2段1號   
2   中山一派出所   Zhongshan First Police Station   104    臺北市中山區中山北路1段110號   
3   中山二派出所  Zhongshan Second Police Station   104     臺北市中山區中山北路2段90號   
4    圓山派出所          Yuanshan Police Staticn   104     臺北市中山區中山北路3段62號   
5   長春路派出所     Changchun Rd. Police Station   104       臺北市中山區長春路206號   
6  長安東路派出所    Changan E. Rd. Police Station   104    臺北市中山區長安東路2段165號   
7   民權一派出所     Minquan First Police Station   104  臺北市中山區新生北路2段127之1號   
8   建國路派出所           Jianguo Police Station   104      臺北市中山區民族東路284號   
9    大直派出所             Dazhi Police Station   104       臺北市中山區北安路456號   

            電話      POINT_X      POINT_Y  
1  02 25412491  302750.6974  2771704.464  
2  02 25519321  302613.5457  2771415.780  
3  02 25517771  302727.2356  2772263.722  
4  02 25969433  302834.9838  2773933.985  
5  02 25062289  304083.3089  2771936.628  
6  02 27735207  304542.2421  2771254.798  
7  02 25314672  303266.0302  2772517.502  
8  02 25099774  304074.2363  2773416.496  
9  02 25332984  304885.9044  2774696.884